name: on_ticos_framework_publish
run-name: ${{ github.actor }} is publishing the codegen path ğŸš€
on:
  push:
    tags:
      - 'v*'
jobs:
  publish-codegen:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@master
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸš€ create release"
      - name: Create release
        uses: meeDamian/github-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          gzip: folders
          files: scripts/codegen/
          allow_override: true
      - run: echo "ğŸ This job's status is ${{ job.status }}."
